### ISSUE TITLE
Toggle_Defender.bat Not Working

### ISSUE THREAD

**Issue by abdullah-erturk** [AveYo/LeanAndMean#1]
**Toggle Defender Not Working on Windows 10/11** 

![Toggle_Defender](https://user-images.githubusercontent.com/54866587/153940931-6d6a5e19-4b31-43f6-9041-d47d641f70e0.PNG)
1

**Comment by AveYo** [comment]
<details> 
  <summary>Not surprising that microsoft have fake-positived the script again and again  </summary> 

  Yet Defender can be fully [uninstalled in 10](https://gist.github.com/AveYo/78386c56e87fc9780bd67c50037d20fe) and service [neutered in 11](https://gist.github.com/AveYo/93ca63bc1334e7109e3b4c646a30f593) with the oldest trick in the book - tamper protection or not  
</details>


Script still usable, just turn off Tamper Protection and Realtime Protection first,  
then enter the code directly into powershell
